name: Deploy to Linux Server

on:
  push:
    branches:
      - master  # or main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            export NVM_DIR="/home/deployportfolio/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            cd /var/www/andrewc.dev/src || exit 1
            git reset --hard origin/master
            git clean -fd
            git pull origin master
            npm install --production
            npm run build
            rm -rf /var/www/andrewc.dev/public/*
            cp -r build/* /var/www/andrewc.dev/public/
            chown -R www-data:www-data /var/www/andrewc.dev/public
            find /var/www/andrewc.dev/public -type d -exec chmod 755 {} \;
            find /var/www/andrewc.dev/public -type f -exec chmod 644 {} \;
